export type Product = {
  slug: string;
  name: string;
  code?: string;
  category: string;
  image: string;
  gallery?: string[];
  description: string;
  material: string;
  moq: number;
  colors: string[];
  features: string[];
};

export const categories = [
  "Baseball Caps",
  "Trucker Hats",
  "Bucket Hats",
  "Visors",
  "Camp Caps",
  "Running Caps",
  "Cadet Caps",
  "Outdoor Caps",
  "Winter Hats",
];

export const sampleProducts: Product[] = [
  {
    slug: "souvenir-patch-snapback",
    name: "Souvenir Patch Snapback",
    code: "B0036",
    category: "Trucker Hats",
    image: "/images/products/souvenir-patch-snapback.jpg",
    gallery: [
      "/images/products/souvenir-patch-snapback-2.jpg",
      "/images/products/souvenir-patch-snapback-3.jpg",
      "/images/products/souvenir-patch-snapback-4.jpg",
      "/images/products/souvenir-patch-snapback-5.jpg",
    ],
    description:
      "An arched souvenir patch on the front, a gold twisted rope across the brim and a laurel sprig either side — three embroidered details that make a commemorative cap. The words, year and emblem inside the patch are all yours — events, anniversaries, clubs.",
    material: "Cotton twill",
    moq: 50,
    colors: [
      "Navy",
      "black",
      "off-white",
      "olive",
    ],
    features: [
      "5-panel snapback, flat brim",
      "Arched souvenir patch, flat embroidery",
      "Gold twisted rope across the brim",
      "Laurel embroidery either side of the brim",
      "Five solid panels, matching snapback",
      "Size: One size · snapback",
    ],
  },
  {
    slug: "two-tone-raw-edge-applique-cap",
    name: "Two-Tone Raw-Edge Appliqué Cap",
    code: "B0037",
    category: "Baseball Caps",
    image: "/images/products/two-tone-raw-edge-applique-cap.jpg",
    gallery: [
      "/images/products/two-tone-raw-edge-applique-cap-2.jpg",
      "/images/products/two-tone-raw-edge-applique-cap-3.jpg",
      "/images/products/two-tone-raw-edge-applique-cap-4.jpg",
      "/images/products/two-tone-raw-edge-applique-cap-5.jpg",
    ],
    description:
      "Raw-edge appliqué letters run from the crown across the seam and onto the brim, over a two-tone body — the letters match the side panels so it reads as one. Both the big letters and the script line take your own words.",
    material: "Cotton twill, light wash",
    moq: 50,
    colors: [
      "Olive/stone",
      "ecru/black",
      "ecru/red",
      "navy/ecru",
    ],
    features: [
      "6-panel ball cap, contrast panels",
      "Raw-edge appliqué crossing the crown-to-brim seam",
      "Front and brim in one colour, sides and back in another",
      "Fine script embroidery above",
      "Four rows of brim topstitch",
      "Size: One size · metal slider",
    ],
  },
  {
    slug: "two-tone-washed-dad-cap",
    name: "Two-Tone Washed Dad Cap",
    code: "B0038",
    category: "Baseball Caps",
    image: "/images/products/two-tone-washed-dad-cap.jpg",
    gallery: [
      "/images/products/two-tone-washed-dad-cap-2.jpg",
      "/images/products/two-tone-washed-dad-cap-3.jpg",
      "/images/products/two-tone-washed-dad-cap-4.jpg",
      "/images/products/two-tone-washed-dad-cap-5.jpg",
    ],
    description:
      "Body in one colour, brim and button in another, with a chubby lowercase wordmark outlined in contrast — relaxed 90s feel. Your wordmark, and your choice of the two colours.",
    material: "Garment-washed cotton twill",
    moq: 50,
    colors: [
      "Black/mustard",
      "navy/khaki",
      "forest/ecru",
    ],
    features: [
      "6-panel washed dad cap, contrast brim",
      "Contrast brim and button",
      "Rounded wordmark with contrast outline",
      "Unstructured crown, garment washed",
      "Self-fabric strap, antique brass clasp",
      "Size: One size · antique brass clasp",
    ],
  },
  {
    slug: "double-zip-brim-cap",
    name: "Double Zipper Brim Cap",
    code: "B0039",
    category: "Baseball Caps",
    image: "/images/products/double-zip-brim-cap.jpg",
    gallery: [
      "/images/products/double-zip-brim-cap-2.jpg",
      "/images/products/double-zip-brim-cap-3.jpg",
      "/images/products/double-zip-brim-cap-4.jpg",
      "/images/products/double-zip-brim-cap-5.jpg",
    ],
    description:
      "A slanted metal zip set into each side of the brim, only the teeth and a slim pull showing — all-black and minimal, the detail is on the brim. The zip pulls and back buckle can both carry your mark.",
    material: "Fine cotton twill",
    moq: 50,
    colors: [
      "Black/gunmetal",
      "black/silver",
      "ecru/gunmetal",
    ],
    features: [
      "6-panel structured ball cap",
      "Two zips inset into the brim",
      "Slim plain pulls — can be engraved",
      "Structured six-panel crown",
      "Clean sides, no marks",
      "Size: One size · metal buckle",
    ],
  },
  {
    slug: "ripped-piercing-denim-cap",
    name: "Ripped Piercing Denim Cap",
    code: "B0040",
    category: "Baseball Caps",
    image: "/images/products/ripped-piercing-denim-cap.jpg",
    gallery: [
      "/images/products/ripped-piercing-denim-cap-2.jpg",
      "/images/products/ripped-piercing-denim-cap-3.jpg",
      "/images/products/ripped-piercing-denim-cap-4.jpg",
      "/images/products/ripped-piercing-denim-cap-5.jpg",
    ],
    description:
      "Pierced all over — safety pins, rings, small spikes and a binder clip on the brim — with ripped panels and a shredded brim edge. The front word is yours; hardware placement and count can change.",
    material: "Washed denim",
    moq: 50,
    colors: [
      "Washed black",
      "ecru",
      "blue",
      "charcoal",
    ],
    features: [
      "6-panel washed denim dad cap",
      "Pins, rings, spikes and a brim clip",
      "Ripped crown, shredded brim edge",
      "Faded washed black",
      "Arched flat-embroidered word",
      "Size: One size · black metal slider",
    ],
  },
  {
    slug: "gradient-bleached-denim-cap",
    name: "Gradient Bleached Denim Cap",
    code: "B0045",
    category: "Baseball Caps",
    image: "/images/products/gradient-bleached-denim-cap.jpg",
    gallery: [
      "/images/products/gradient-bleached-denim-cap-2.jpg",
      "/images/products/gradient-bleached-denim-cap-3.jpg",
      "/images/products/gradient-bleached-denim-cap-4.jpg",
      "/images/products/gradient-bleached-denim-cap-5.jpg",
    ],
    description:
      "Bleached from mid-blue at the crown to almost white at the brim, worn through at the edges, with a white serif line across the front. The front line becomes your slogan or name.",
    material: "Stretch washed denim",
    moq: 50,
    colors: [
      "Gradient bleached blue",
    ],
    features: [
      "6-panel denim dad cap",
      "Gradient bleach, crown to brim",
      "Worn edges showing white yarn",
      "White serif embroidery across the front",
      "Unstructured, sits close",
      "Size: One size · silver slider",
    ],
  },
  {
    slug: "stripe-over-brim-soft-cap",
    name: "Stripe-Over-Brim Soft Cap",
    code: "B0046",
    category: "Baseball Caps",
    image: "/images/products/stripe-over-brim-soft-cap.jpg",
    gallery: [
      "/images/products/stripe-over-brim-soft-cap-2.jpg",
      "/images/products/stripe-over-brim-soft-cap-3.jpg",
      "/images/products/stripe-over-brim-soft-cap-4.jpg",
      "/images/products/stripe-over-brim-soft-cap-5.jpg",
    ],
    description:
      "Two raised white stripes run from the crown right onto the brim, with an oval raised-embroidery patch on the front — sporty and graphic. The patch text is yours; stripe colour can change.",
    material: "Cotton twill",
    moq: 50,
    colors: [
      "Black",
      "ecru",
      "navy",
      "charcoal",
    ],
    features: [
      "6-panel low-profile soft cap",
      "Raised stripes from crown onto brim",
      "Oval raised-embroidery patch",
      "Low soft crown, pre-curved brim",
      "Strap with silver D-ring",
      "Size: One size · silver D-ring",
    ],
  },
  {
    slug: "chain-stitch-pillbox-cap",
    name: "Chain-Stitch Pillbox Cap",
    code: "J0041",
    category: "Cadet Caps",
    image: "/images/products/chain-stitch-pillbox-cap.jpg",
    gallery: [
      "/images/products/chain-stitch-pillbox-cap-2.jpg",
      "/images/products/chain-stitch-pillbox-cap-3.jpg",
      "/images/products/chain-stitch-pillbox-cap-4.jpg",
      "/images/products/chain-stitch-pillbox-cap-5.jpg",
    ],
    description:
      "Oversized varsity letters wrap all the way round the crown in chain stitch — a low pillbox shape with a short, almost flat brim. The word around the crown becomes your name.",
    material: "Cotton-nylon twill, light wash",
    moq: 50,
    colors: [
      "Black",
      "indigo",
      "ecru",
      "dark olive",
    ],
    features: [
      "Low flat-top pillbox cap, short brim",
      "Letters wrap the whole crown",
      "Chain-stitch embroidery, textured",
      "Low flat top, short brim",
      "Plain back, no marks",
      "Size: One size · snap strap",
    ],
  },
  {
    slug: "surf-cap-chin-strap",
    name: "Surf Cap with Chin Strap",
    code: "M0011",
    category: "Running Caps",
    image: "/images/products/surf-cap-chin-strap.jpg",
    gallery: [
      "/images/products/surf-cap-chin-strap-2.jpg",
      "/images/products/surf-cap-chin-strap-3.jpg",
      "/images/products/surf-cap-chin-strap-4.jpg",
      "/images/products/surf-cap-chin-strap-5.jpg",
    ],
    description:
      "A neoprene Y-shaped chin strap buckles under the chin, with a short flat brim — made to stay on through surf, paddling and swimming. The side text is yours — for surf shops and water clubs.",
    material: "Matte nylon",
    moq: 50,
    colors: [
      "Navy",
      "khaki",
      "steel green",
      "charcoal",
    ],
    features: [
      "6-panel water-sport cap, short brim",
      "Neoprene Y-shaped chin strap",
      "Short flat brim, multi-row topstitch",
      "Light matte nylon",
      "Small side embroidery",
      "Size: One size · buckle and chin strap",
    ],
  },
  {
    slug: "frayed-edge-denim-bucket-hat",
    name: "Frayed-Edge Denim Bucket Hat",
    code: "Y0042",
    category: "Bucket Hats",
    image: "/images/products/frayed-edge-denim-bucket-hat.jpg",
    gallery: [
      "/images/products/frayed-edge-denim-bucket-hat-2.jpg",
      "/images/products/frayed-edge-denim-bucket-hat-3.jpg",
      "/images/products/frayed-edge-denim-bucket-hat-4.jpg",
      "/images/products/frayed-edge-denim-bucket-hat-5.jpg",
    ],
    description:
      "A full ring of frayed, blown-out edge round the soft brim, with a small raised embroidery on the front — easy washed denim. The small front mark becomes yours.",
    material: "Washed cotton denim",
    moq: 50,
    colors: [
      "Light blue denim",
      "washed black",
      "ecru canvas",
    ],
    features: [
      "Wide-brim denim bucket hat",
      "Frayed edge all round the brim",
      "Same colour inside and out",
      "Small raised embroidery",
      "Navy adjustable cord",
      "Size: One size · adjustable cord",
    ],
  },
  {
    slug: "teddy-earflap-wool-bucket-hat",
    name: "Teddy Earflap Wool Bucket Hat",
    code: "Y0043",
    category: "Bucket Hats",
    image: "/images/products/teddy-earflap-wool-bucket-hat.jpg",
    gallery: [
      "/images/products/teddy-earflap-wool-bucket-hat-2.jpg",
      "/images/products/teddy-earflap-wool-bucket-hat-3.jpg",
      "/images/products/teddy-earflap-wool-bucket-hat-4.jpg",
      "/images/products/teddy-earflap-wool-bucket-hat-5.jpg",
    ],
    description:
      "Teddy fleece under the brim, two wool-and-fleece earflaps and suede ties that knot in a bow — a warm winter bucket. The small front line becomes yours.",
    material: "Wool-blend felt, teddy fleece",
    moq: 50,
    colors: [
      "Chocolate",
      "oat",
      "charcoal",
      "black",
    ],
    features: [
      "Wool bucket hat with earflaps",
      "Teddy fleece underbrim",
      "Wool earflaps lined with fleece",
      "Suede ties with a bow",
      "Small flat embroidery on the front",
      "Size: One size · suede ties",
    ],
  },
  {
    slug: "serif-wordmark-washed-cap",
    name: "Serif Wordmark Washed Cap",
    code: "B0021",
    category: "Baseball Caps",
    image: "/images/products/serif-wordmark-washed-cap.jpg",
    gallery: [
      "/images/products/serif-wordmark-washed-cap-2.jpg",
      "/images/products/serif-wordmark-washed-cap-3.jpg",
      "/images/products/serif-wordmark-washed-cap-4.jpg",
      "/images/products/serif-wordmark-washed-cap-5.jpg",
    ],
    description:
      "An oversized serif wordmark runs edge to edge across the front, letters set on uneven baselines for a hand-set look. Wordmark replaced with your brand name — same block, different label.",
    material: "Washed cotton twill",
    moq: 50,
    colors: [
      "Washed black",
      "washed olive",
      "washed khaki",
    ],
    features: [
      "6-panel unstructured low-profile cap",
      "Satin-stitch embroidery direct on crown",
      "Low soft crown, near-flat brim",
      "Washed finish with worn brim edge",
      "Antique silver metal slider",
      "Size: One size · metal slider",
    ],
  },
  {
    slug: "tire-stripe-mesh-trucker",
    name: "Tire Stripe Mesh Trucker",
    code: "B0024",
    category: "Trucker Hats",
    image: "/images/products/tire-stripe-mesh-trucker.jpg",
    gallery: [
      "/images/products/tire-stripe-mesh-trucker-2.jpg",
      "/images/products/tire-stripe-mesh-trucker-3.jpg",
      "/images/products/tire-stripe-mesh-trucker-4.jpg",
      "/images/products/tire-stripe-mesh-trucker-5.jpg",
    ],
    description:
      "A dry-brushed stripe group runs across the front — broken, uneven edges that read as worn, not printed. Front logo area open for embroidery or print.",
    material: "Woven front panels, hex mesh back",
    moq: 50,
    colors: [
      "White with gold & burgundy stripes",
    ],
    features: [
      "Trucker cap, mesh back, snapback",
      "Structured front, six-panel hex mesh back",
      "Curved brim with multi-row topstitch",
      "Dry-brush distressed stripe artwork",
      "Colour-matched plastic snapback",
      "Size: One size · 7-position snapback",
    ],
  },
  {
    slug: "sherpa-trim-bucket-hat",
    name: "Sherpa Trim Bucket Hat",
    code: "Y0002",
    category: "Bucket Hats",
    image: "/images/products/sherpa-trim-bucket-hat.jpg",
    gallery: [
      "/images/products/sherpa-trim-bucket-hat-2.jpg",
      "/images/products/sherpa-trim-bucket-hat-3.jpg",
      "/images/products/sherpa-trim-bucket-hat-4.jpg",
      "/images/products/sherpa-trim-bucket-hat-5.jpg",
    ],
    description:
      "Three bands of sherpa trim cut across a low flat-top crown — a two-material silhouette that reads from a distance. Blank crown — open for embroidery, print or patch.",
    material: "100% polyester, sherpa trim",
    moq: 50,
    colors: [
      "Black with olive trim",
    ],
    features: [
      "Low flat-top bucket hat",
      "Flat oval top, short outward brim",
      "Sherpa trim at top, mid-body and brim edge",
      "Multi-row parallel brim stitching",
      "Clean blank surface for branding",
      "Size: 57 cm (other sizes to order)",
      "Custom colours available on request",
    ],
  },
  {
    slug: "sunglass-slot-sport-visor",
    name: "Sunglass Slot Sport Visor",
    code: "K0022",
    category: "Visors",
    image: "/images/products/sunglass-slot-sport-visor.jpg",
    gallery: [
      "/images/products/sunglass-slot-sport-visor-2.jpg",
      "/images/products/sunglass-slot-sport-visor-3.jpg",
    ],
    description:
      "A slot at each side holds sunglasses while you run — the detail buyers remember when they pick this one up. Front band and brim side both take your logo.",
    material: "Mesh knit, self-fabric covered brim",
    moq: 50,
    colors: [
      "Black",
    ],
    features: [
      "Open-crown sport visor",
      "Side slot sized for sunglass temples",
      "Open crown, mesh knit band",
      "Curved brim in matching fabric",
      "Hook-and-loop rear closure",
      "Size: One size · hook-and-loop",
      "Custom colours available on request",
    ],
  },
  {
    slug: "raw-edge-letter-washed-cap",
    name: "Raw-Edge Letter Washed Cap",
    code: "B0031",
    category: "Baseball Caps",
    image: "/images/products/raw-edge-letter-washed-cap.jpg",
    gallery: [
      "/images/products/raw-edge-letter-washed-cap-2.jpg",
      "/images/products/raw-edge-letter-washed-cap-3.jpg",
      "/images/products/raw-edge-letter-washed-cap-4.jpg",
      "/images/products/raw-edge-letter-washed-cap-5.jpg",
    ],
    description:
      "One oversized letter cut from raw cotton twill and stitched straight onto the front — no bound edge, threads left loose. The rougher it is, the better it reads. One letter, one brand — the front takes your initial.",
    material: "Garment-washed cotton twill",
    moq: 50,
    colors: [
      "Washed black",
      "burgundy",
      "navy",
    ],
    features: [
      "6-panel washed ball cap",
      "Raw-edge appliqué letter, one line of stitching inside the outline",
      "Six-panel soft crown, curved brim, clean brim edge",
      "Garment-washed cotton twill",
      "Webbing strap with antique brass clasp",
      "Size: One size · webbing strap, antique brass clasp",
    ],
  },
  {
    slug: "outline-letter-vintage-washed-cap",
    name: "Outline Letter Vintage Washed Cap",
    code: "B0034",
    category: "Baseball Caps",
    image: "/images/products/outline-letter-vintage-washed-cap.jpg",
    gallery: [
      "/images/products/outline-letter-vintage-washed-cap-2.jpg",
      "/images/products/outline-letter-vintage-washed-cap-3.jpg",
      "/images/products/outline-letter-vintage-washed-cap-4.jpg",
      "/images/products/outline-letter-vintage-washed-cap-5.jpg",
    ],
    description:
      "An outline-only letter that fills most of the front, stitched in short broken segments so the crown fabric shows through — then the brim edge is worn down on purpose. The letter and the brim script both take your own mark.",
    material: "Garment-washed cotton",
    moq: 50,
    colors: [
      "Washed black",
      "navy",
      "khaki",
      "off-white",
    ],
    features: [
      "6-panel vintage washed ball cap",
      "Segmented outline embroidery, no fill",
      "Script embroidery along the brim curve",
      "Brim edge distressed to show the lining",
      "Six-panel soft crown, webbing strap",
      "Size: One size · webbing strap",
    ],
  },
  {
    slug: "felt-initials-wool-cap",
    name: "Felt Initials Wool Cap",
    code: "B0032",
    category: "Baseball Caps",
    image: "/images/products/felt-initials-wool-cap.jpg",
    gallery: [
      "/images/products/felt-initials-wool-cap-2.jpg",
      "/images/products/felt-initials-wool-cap-3.jpg",
      "/images/products/felt-initials-wool-cap-4.jpg",
      "/images/products/felt-initials-wool-cap-5.jpg",
    ],
    description:
      "Felt letters cut and stitched onto a wool-blend crown, with the brim in a contrast colour. A winter cap that sits a class above the cotton ones. Three letters is the classic team format — yours go here.",
    material: "Wool-blend felt",
    moq: 50,
    colors: [
      "Heather grey with navy",
      "navy with grey",
      "oatmeal with brown",
    ],
    features: [
      "6-panel wool-blend cap, contrast brim",
      "Felt appliqué letters with edge stitching",
      "Contrast wool brim, no topstitch",
      "Antique brass eyelets and clasp",
      "Full round crown, fuller than a dad cap",
      "Size: One size · antique brass clasp",
    ],
  },
  {
    slug: "frayed-seam-washed-denim-cap",
    name: "Frayed Seam Washed Denim Cap",
    code: "B0023",
    category: "Baseball Caps",
    image: "/images/products/frayed-seam-washed-denim-cap.jpg",
    gallery: [
      "/images/products/frayed-seam-washed-denim-cap-2.jpg",
      "/images/products/frayed-seam-washed-denim-cap-3.jpg",
      "/images/products/frayed-seam-washed-denim-cap-4.jpg",
      "/images/products/frayed-seam-washed-denim-cap-5.jpg",
    ],
    description:
      "Three destructive finishes in one cap: exposed frayed seams, a broken-down brim edge and raw-edge appliqué letters. Appliqué letters swapped for your own text or logo.",
    material: "Washed denim, cotton",
    moq: 50,
    colors: [
      "Misty blue",
    ],
    features: [
      "6-panel baseball cap, curved brim",
      "Raw frayed seams along every panel line",
      "Heavily distressed brim edge",
      "Raw-edge denim appliqué with twin outline stitch",
      "Self-fabric strap, metal slider",
      "Size: One size · adjustable strap",
      "Custom colours available on request",
    ],
  },
  {
    slug: "studded-washed-denim-cap",
    name: "Studded Washed Denim Cap",
    code: "B0008",
    category: "Baseball Caps",
    image: "/images/products/studded-washed-denim-cap.jpg",
    gallery: [
      "/images/products/studded-washed-denim-cap-2.jpg",
      "/images/products/studded-washed-denim-cap-3.jpg",
      "/images/products/studded-washed-denim-cap-4.jpg",
      "/images/products/studded-washed-denim-cap-5.jpg",
    ],
    description:
      "Studs run along the front and side panel seams and around the brim edge, over a heavily washed denim ground. Artwork is replaced with your own — the studs and the wash stay.",
    material: "Washed denim, cotton",
    moq: 50,
    colors: [
      "Washed indigo",
    ],
    features: [
      "6-panel baseball cap",
      "Studs on front and side seams and brim edge",
      "Embroidered eyelets, not metal grommets",
      "Heavy garment wash, hand-sanded edges",
      "Single oval metal clasp on the adjuster",
      "Size: One size · adjustable",
      "Custom colours available on request",
    ],
  },
  {
    slug: "studded-brim-pigment-cap",
    name: "Studded Brim Pigment Cap",
    code: "B0025",
    category: "Baseball Caps",
    image: "/images/products/studded-brim-pigment-cap.jpg",
    gallery: [
      "/images/products/studded-brim-pigment-cap-2.jpg",
      "/images/products/studded-brim-pigment-cap-3.jpg",
      "/images/products/studded-brim-pigment-cap-4.jpg",
      "/images/products/studded-brim-pigment-cap-5.jpg",
    ],
    description:
      "A ring of dome studs along the brim edge, outline-only lettering, and a woven label at the back — three hardware and craft details in one block. Letters and woven label both carry your own text.",
    material: "Pigment-dyed washed cotton twill",
    moq: 50,
    colors: [
      "Charcoal",
    ],
    features: [
      "6-panel soft crown, near-flat brim",
      "Dome studs set evenly around brim edge",
      "Outline embroidery, crown fabric showing through",
      "Pigment dye with natural tonal variation",
      "Woven label beside adjuster",
      "Size: One size · adjustable strap",
      "Custom colours available on request",
    ],
  },
  {
    slug: "double-piping-washed-cap",
    name: "Double Piping Washed Cap",
    code: "B0018",
    category: "Baseball Caps",
    image: "/images/products/double-piping-washed-cap.jpg",
    gallery: [
      "/images/products/double-piping-washed-cap-2.jpg",
      "/images/products/double-piping-washed-cap-3.jpg",
      "/images/products/double-piping-washed-cap-4.jpg",
      "/images/products/double-piping-washed-cap-5.jpg",
    ],
    description:
      "A narrow contrast piping is seamed into the crown's base and runs the full circumference, a second line traces the brim edge, and a rounded PVC patch sits front and centre — three hardware and craft details in one washed cotton cap. The front patch is a placeholder in soft matte PVC — swapped for your own wordmark, same build and size.",
    material: "Washed cotton twill",
    moq: 50,
    colors: [
      "Washed black",
      "washed navy",
      "washed brick red",
      "washed latte",
    ],
    features: [
      "6-panel unstructured low-profile dad cap, curved brim",
      "Piping set into the crown base seam, continuous around the back",
      "Second piping line along the brim edge, meeting the crown line at each side",
      "Washed cotton twill with natural tonal fading",
      "Antique metal slider with webbing strap at the back",
      "Size: One size · metal slider",
    ],
  },
  {
    slug: "utility-pocket-camp-cap",
    name: "Utility Pocket Camp Cap",
    code: "J0029",
    category: "Camp Caps",
    image: "/images/products/utility-pocket-camp-cap.jpg",
    gallery: [
      "/images/products/utility-pocket-camp-cap-2.jpg",
      "/images/products/utility-pocket-camp-cap-3.jpg",
      "/images/products/utility-pocket-camp-cap-4.jpg",
      "/images/products/utility-pocket-camp-cap-5.jpg",
    ],
    description:
      "A working flap pocket sits on the front panel — for a card, a set of earplugs, or purely as a detail. The language here is tool, not logo. The flap is a natural place for a woven label or an embroidered mark.",
    material: "Windproof woven",
    moq: 50,
    colors: [
      "Olive",
    ],
    features: [
      "5-panel camp cap with flap pocket",
      "Front flap pocket, opens and closes",
      "Low crown with a flat brim",
      "Metal eyelets on the side panels",
      "Webbing strap adjuster",
      "Size: One size · webbing strap",
      "Custom colours available on request",
    ],
  },
  {
    slug: "lightweight-running-cap",
    name: "Lightweight Running Cap",
    code: "M0007",
    category: "Running Caps",
    image: "/images/products/lightweight-running-cap.jpg",
    gallery: [
      "/images/products/lightweight-running-cap-2.jpg",
      "/images/products/lightweight-running-cap-3.jpg",
      "/images/products/lightweight-running-cap-4.jpg",
      "/images/products/lightweight-running-cap-5.jpg",
    ],
    description:
      "Light in the hand with a soft brim that rolls into a pocket — built for runners, blank for branding. Clean front panel — the easiest base for a team or race logo.",
    material: "Stretch woven polyester",
    moq: 50,
    colors: [
      "Black",
      "off-white",
    ],
    features: [
      "Running cap, soft brim",
      "Lightweight stretch woven shell",
      "Soft brim, rolls and recovers",
      "Elastic cord rear adjustment",
      "Fully blank, no branding applied",
      "Size: One size · elastic cord",
      "Custom colours available on request",
    ],
  },
  {
    slug: "sunglass-slot-long-brim-sport-cap",
    name: "Sunglass Slot Long-Brim Sport Cap",
    code: "M0027",
    category: "Running Caps",
    image: "/images/products/sunglass-slot-long-brim-sport-cap.jpg",
    gallery: [
      "/images/products/sunglass-slot-long-brim-sport-cap-2.jpg",
      "/images/products/sunglass-slot-long-brim-sport-cap-3.jpg",
      "/images/products/sunglass-slot-long-brim-sport-cap-4.jpg",
      "/images/products/sunglass-slot-long-brim-sport-cap-5.jpg",
    ],
    description:
      "A triangular mesh window on each side takes the arm of a pair of sunglasses — they stay on the cap instead of in a pocket. Blank front panel. The glasses shown are a prop, not part of the build.",
    material: "Lightweight nylon woven",
    moq: 50,
    colors: [
      "Light grey",
    ],
    features: [
      "5-panel sport cap, long brim",
      "Side mesh windows sized for sunglass arms",
      "Long brim for extra shade",
      "Lightweight quick-dry nylon woven",
      "Elastic cord adjuster with reflective trim",
      "Size: One size · elastic cord",
      "Custom colours available on request",
    ],
  },
  {
    slug: "washed-denim-cadet-cap",
    name: "Washed Denim Cadet Cap",
    code: "J0004",
    category: "Cadet Caps",
    image: "/images/products/washed-denim-cadet-cap.jpg",
    gallery: [
      "/images/products/washed-denim-cadet-cap-2.jpg",
      "/images/products/washed-denim-cadet-cap-3.jpg",
      "/images/products/washed-denim-cadet-cap-4.jpg",
      "/images/products/washed-denim-cadet-cap-5.jpg",
    ],
    description:
      "A flat military crown wrapped in raw-edge appliqué lettering that carries from the front around to both sides. Lettering is a placeholder — your own word or logo in its place.",
    material: "Washed denim, cotton",
    moq: 50,
    colors: [
      "Denim blue",
      "charcoal",
      "olive",
    ],
    features: [
      "Flat-top cadet cap",
      "Round flat top, straight cap wall",
      "Raw-edge appliqué with white outline embroidery",
      "Distressed brim showing white warp threads",
      "Washed-down denim hand",
      "Size: One size · adjustable",
    ],
  },
  {
    slug: "neck-shade-jet-cap",
    name: "Neck Shade Jet Cap",
    code: "PJ0005",
    category: "Outdoor Caps",
    image: "/images/products/neck-shade-jet-cap.jpg",
    gallery: [
      "/images/products/neck-shade-jet-cap-2.jpg",
      "/images/products/neck-shade-jet-cap-3.jpg",
      "/images/products/neck-shade-jet-cap-4.jpg",
      "/images/products/neck-shade-jet-cap-5.jpg",
    ],
    description:
      "Two hats in one: shade attached for the water, shade off for the walk back. Graduated perforations run down each side panel. Blank panels front and side — print or embroidery to your artwork.",
    material: "Matte water-repellent woven",
    moq: 50,
    colors: [
      "Black",
    ],
    features: [
      "5-panel jet cap, detachable shade",
      "Five-panel jet crown, soft top",
      "Laser perforation graduated large to small",
      "Detachable neck shade, 3-point hook-and-loop",
      "Rear drawcord with barrel adjuster",
      "Size: One size · rear drawcord",
      "Custom colours available on request",
    ],
  },
  {
    slug: "gathered-crown-sun-hat",
    name: "Gathered Crown Sun Hat",
    code: "Y0028",
    category: "Bucket Hats",
    image: "/images/products/gathered-crown-sun-hat.jpg",
    gallery: [
      "/images/products/gathered-crown-sun-hat-2.jpg",
      "/images/products/gathered-crown-sun-hat-3.jpg",
      "/images/products/gathered-crown-sun-hat-4.jpg",
    ],
    description:
      "A gathered band around the crown gives the hat a skirt-like fall; the underside of the brim runs a contrast colour with a fine piped edge — the part you only see when the brim lifts. Completely blank — no marks anywhere, ready for your own embroidery.",
    material: "Soft woven",
    moq: 50,
    colors: [
      "Four-colour contrast range",
    ],
    features: [
      "Wide-brim sun hat, gathered crown",
      "Gathered band around the crown",
      "Contrast brim underside with a piped edge",
      "Soft body, packs flat",
      "Flat webbing chin cord, removable",
      "Size: One size · removable chin cord",
    ],
  },
  {
    slug: "contrast-brim-bucket-hat",
    name: "Contrast Brim Bucket Hat",
    code: "Y0035",
    category: "Bucket Hats",
    image: "/images/products/contrast-brim-bucket-hat.jpg",
    gallery: [
      "/images/products/contrast-brim-bucket-hat-2.jpg",
      "/images/products/contrast-brim-bucket-hat-3.jpg",
      "/images/products/contrast-brim-bucket-hat-4.jpg",
      "/images/products/contrast-brim-bucket-hat-5.jpg",
    ],
    description:
      "Crown and brim sit in two contrast colours, and the brim carries a ring of six to eight concentric topstitch lines running its full width — the detail that catches the eye first. Completely blank — the crown, brim and band carry no branding, ready for your own embroidery or print.",
    material: "100% polyester",
    moq: 50,
    colors: [
      "Sand with navy brim",
      "Light grey with charcoal brim",
      "Cream with caramel brim",
      "Khaki with olive brim",
    ],
    features: [
      "Wide-brim bucket hat, adjustable chin cord",
      "Gathered band at the crown base in the brim colour, edged with tonal piping",
      "Concentric topstitch rings across the full brim width",
      "Two bronze-tone eyelets at the sides",
      "Adjustable cord chin strap with a toggle",
      "Size: One size · 56–62 cm, adjustable cord",
    ],
  },
  {
    slug: "stretch-woven-visor",
    name: "Stretch Woven Visor",
    code: "K0003",
    category: "Visors",
    image: "/images/products/stretch-woven-visor.jpg",
    gallery: [
      "/images/products/stretch-woven-visor-2.jpg",
      "/images/products/stretch-woven-visor-3.jpg",
      "/images/products/stretch-woven-visor-4.jpg",
      "/images/products/stretch-woven-visor-5.jpg",
    ],
    description:
      "A wide woven headband with a fine matte face, black mesh inside, and a twin elastic loop adjuster at the back. Clean front band — your logo embroidered or printed.",
    material: "88% recycled polyester / 12% elastane",
    moq: 50,
    colors: [
      "Black",
      "white",
    ],
    features: [
      "Open-crown visor",
      "Open crown, wide structured band",
      "Curved brim, twin parallel topstitch",
      "Black mesh interior on both colourways",
      "Dual elastic loop rear adjustment",
      "Size: 57 cm · adjustable",
    ],
  },
  {
    slug: "corduroy-sherpa-earflap-cap",
    name: "Corduroy Sherpa Earflap Cap",
    code: "D0006",
    category: "Winter Hats",
    image: "/images/products/corduroy-sherpa-earflap-cap.jpg",
    gallery: [
      "/images/products/corduroy-sherpa-earflap-cap-2.jpg",
      "/images/products/corduroy-sherpa-earflap-cap-3.jpg",
      "/images/products/corduroy-sherpa-earflap-cap-4.jpg",
      "/images/products/corduroy-sherpa-earflap-cap-5.jpg",
    ],
    description:
      "Worn two ways — flaps down for cold, folded up for town. Wide-wale corduroy over a quilted sherpa lining. Blank shell — embroidery or woven patch to your artwork.",
    material: "100% cotton corduroy, sherpa lining",
    moq: 50,
    colors: [
      "Brown with cream sherpa",
    ],
    features: [
      "Earflap winter cap",
      "Wide-wale corduroy shell",
      "Sherpa-lined earflaps, fold up or down",
      "Quilted insulating lining",
      "Blank body, no branding applied",
      "Size: 57 cm (adjuster optional)",
      "Custom colours available on request",
    ],
  },
  {
    slug: "faux-fur-trim-earflap-cap",
    name: "Faux Fur Trim Earflap Cap",
    code: "B0030",
    category: "Winter Hats",
    image: "/images/products/faux-fur-trim-earflap-cap.jpg",
    gallery: [
      "/images/products/faux-fur-trim-earflap-cap-2.jpg",
      "/images/products/faux-fur-trim-earflap-cap-3.jpg",
      "/images/products/faux-fur-trim-earflap-cap-4.jpg",
      "/images/products/faux-fur-trim-earflap-cap-5.jpg",
    ],
    description:
      "A ring of long faux fur wraps a plain baseball crown — it covers the ears, frames the face, and photographs well. That script on the front is where your own name goes.",
    material: "Woven shell, faux fur trim",
    moq: 50,
    colors: [
      "Brown",
      "off-white",
    ],
    features: [
      "Baseball crown with faux fur trim",
      "Long-pile faux fur trim around the crown",
      "Script embroidery set across the front panel",
      "Woven shell over a quilted lining",
      "Faux fur only — no animal fur is used",
      "Size: One size",
      "Custom colours available on request",
    ],
  },
  {
    slug: "reversible-fleece-trooper-hat",
    name: "Reversible Fleece Trooper Hat",
    code: "LF0033",
    category: "Winter Hats",
    image: "/images/products/reversible-fleece-trooper-hat.jpg",
    gallery: [
      "/images/products/reversible-fleece-trooper-hat-2.jpg",
      "/images/products/reversible-fleece-trooper-hat-3.jpg",
      "/images/products/reversible-fleece-trooper-hat-4.jpg",
      "/images/products/reversible-fleece-trooper-hat-5.jpg",
    ],
    description:
      "Wears both ways — nylon out for a quiet look, fleece out when it gets cold. A one-piece earflap wraps the whole back of the head. Only a small embroidered mark on the front — plenty of room for yours.",
    material: "Crinkle nylon shell, fleece reverse",
    moq: 50,
    colors: [
      "Black with off-white fleece",
      "olive with off-white",
      "caramel with brown",
    ],
    features: [
      "Reversible trooper hat, short brim",
      "Reversible: crinkle nylon one side, fleece the other",
      "One-piece earflap, ear to ear around the back",
      "Short stiff brim",
      "Thin tie cords at the flap ends",
      "Size: One size · tie cords",
    ],
  },
];
